package com.shifterwebapp.shifter.enums;

public enum Skills {

    // CORE BUSINESS SKILLS
    STRATEGIC_THINKING,
    STRATEGIC_PLANNING,
    BUSINESS_DEVELOPMENT,
    PROJECT_MANAGEMENT,
    OPERATION_MANAGEMENT,
    LOGISTICS,
    BUSINESS_MODEL_CREATION,
    RISK_MANAGEMENT,
    STARTUP_METHODOLOGIES,

    // MARKETING & SALES
    MARKETING,
    DIGITAL_MARKETING,
    TRADITIONAL_MARKETING,
    BRANDING,
    SALES,
    SALES_TECHNIQUES,
    B2B_TACTICS,
    B2C_TACTICS,
    SEO,
    GOOGLE_ANALYTICS,
    ECOMMERCE_PLATFORMS,

    // LEADERSHIP & MANAGEMENT
    LEADERSHIP,
    PEOPLE_MANAGEMENT,
    TEAM_BUILDING,
    DELEGATION,
    CONFLICT_RESOLUTION,
    DECISION_MAKING,
    PERFORMANCE_EVALUATION,
    CHANGE_MANAGEMENT,  // Added missing

    // SOFT SKILLS / PERSONAL EFFECTIVENESS
    COMMUNICATION,
    EMOTIONAL_INTELLIGENCE,
    TIME_MANAGEMENT,
    ADAPTABILITY,
    CRITICAL_THINKING,
    CREATIVITY,
    PROBLEM_SOLVING,
    NEGOTIATION,
    PARADIGM_UNDERSTANDING,
    PERCEPTION_MANAGEMENT,
    PERSPECTIVE_SHIFTING,

    // ENTREPRENEURSHIP
    OPPORTUNITY_IDENTIFICATION,
    FUNDRAISING_CAPITAL,
    INNOVATION_MANAGEMENT,

    // TECH & DIGITAL TOOLS
    AI_TOOLS,

    // LEGAL & ETHICS
    BUSINESS_LAW,
    BUSINESS_ETHICS
}
