
services:
  db:
    image: postgres:17
    container_name: shifter-db
    ports:
      - "7781:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - shifter-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  shifter-db-data: