package com.shifterwebapp.shifter.collection.domain.bundle.enums;

public enum PersonalizedBundleType {
    SYSTEM_RECOMMENDATION,      // A recommendation generated by the system
    ADJUSTED_BUNDLE             // A bundle that has been adjusted because a user already has some course from the base bundle
}
