INSERT INTO course (title,
                    description_short,
                    description,
                    description_long,
                    difficulty,
                    duration_hours,
                    price,
                    rating,
                    rating_count,
                    topic)
VALUES ('From Manager to Leader: Empowering People, Managing Processes',
        'Transform your managerial skills into effective leadership.',
        'Learn to lead people and manage processes with proven leadership tools and models.',
        'This course is designed for managers who want to become impactful leaders. It covers the core principles of leadership such as the 3xH’s of generative leadership, the difference between responsibility and guilt, communication strategies, feedback, and models like AB, Min/Max, and SMART objectives. Gain the mindset and practical tools to lead teams effectively, break silos, delegate with confidence, and mentor others.',
        'INTERMEDIATE',
        3,
        29,
        48,
        10,
        'Leadership & Management'),
       ('Business Transformation Blueprint: Crafting the Path to Success',
        'Design and implement successful business transformations.',
        'Master the framework for guiding organizations through structured, sustainable transformation.',
        'This course provides a complete blueprint for driving successful business transformations. You’ll learn to identify when transformation is needed, and why following the proper sequence of steps is critical. We explore the role of middle management, the six core stages of transformation (from purpose to KPIs), and how to establish agile and resilient structures. You’ll also develop a new paradigm and perspective to boost your business’s STABILITY, AGILITY, RESILIENCE, and SUSTAINABILITY.',
        'ADVANCED',
        5.5,
        54,
        49,
        10,
        'Business Strategy & Transformation'),
       ('Business Roadmap for SME’s: A Step-by-Step Guide for Establishing Core Business Foundations for Sustainable Growth',
        'Step-by-step guidance for SMEs to build solid business foundations.',
        'Cut through the noise and build sustainable business foundations with clarity and confidence.',
        'In today’s world of overwhelming information, especially around business growth, marketing, and sales strategies, it’s difficult to know where to begin. This course helps small and medium-sized businesses eliminate that confusion by providing a structured, step-by-step roadmap for building strong business foundations. Through a new paradigm and broadened perspective, you’ll increase your STABILITY, AGILITY, RESILIENCE, and SUSTAINABILITY while gaining clarity on what truly matters for long-term growth.',
        'INTERMEDIATE',
        6,
        35,
        49,
        10,
        'Entrepreneurship & SME Growth'),
       ('Sales Masterclass: Leadership, Communication, and Modern Sales Process',
        'Master modern sales strategies, leadership, and communication.',
        'A complete guide to building elite sales skills, behaviors, and mindset.',
        'This comprehensive masterclass is designed for sales professionals who want to excel in today’s fast-paced and client-centric environment. Learn the role of frontline salespeople, how to build team synergy, and understand the critical difference between being responsible and feeling guilty. Explore how silos hurt sales, how to manage time effectively, and what truly defines high-performance behavior. Master modern sales and negotiation techniques, improve communication and decision-making, and learn to lead with clarity and confidence. Includes practical tools like the AB model and marketing techniques tailored for salespeople.',
        'ADVANCED',
        4,
        29,
        47,
        10,
        'Sales & Communication'),
       ('From Good to Extraordinary: Mastering Skills for Success',
        'Unlock your full potential with practical skills for extraordinary success.',
        'A holistic course for professionals aiming to elevate their effectiveness and mindset.',
        'This course is built for individuals who want to go from good to extraordinary in their personal and professional lives. You’ll explore key topics like perception, time management, managing expectations, and setting smart priorities. Learn and apply powerful tools like the AB and Min/Max models, the SMART objectives model, and the method of deduction. Develop cognitive skills, improve communication maturity, and boost your efficiency in meetings, decision-making, and real-world interactions. Focused on practical results, not just theory.',
        'INTERMEDIATE',
        6,
        35,
        48,
        10,
        'Personal Development & Productivity'),
       ('Winning Markets in 3 Steps: Building a Clear Go-to-Market Strategy',
        'Build a clear, effective go-to-market strategy in just 3 steps.',
        'Learn to target the right clients and approach the market with clarity and confidence.',
        'Without a clear marketing strategy, businesses often drift without direction. This course shows you how to avoid that by creating a precise go-to-market strategy in 3 steps. Define your ideal target client using 8 key characteristics: needs, wants, expectations, challenges, fears, intentions, prejudices, and opportunities. Learn when, where, and how to reach your audience, using tools like the AB model and a quantification method for negotiation and sales. Includes real-world examples to help you implement a clear, winning strategy.',
        'INTERMEDIATE',
        5,
        29,
        49,
        10,
        'Marketing & Sales Strategy'),
       ('Creating Added Value: How to Offer Solutions/Concepts, Instead of Services',
        'Shift from selling services to offering impactful solutions and concepts.',
        'Learn how to transition from offering services to delivering real value through solutions and long-term concepts.',
        'In this course, you’ll learn how to move beyond just offering products or services by creating added value through solutions and concepts. Understand the importance of knowing your target audience, identifying the problems your offering solves, and crafting offers that connect deeply with client needs. We’ll explore the difference between selling a service vs. a solution, and what it means to go a step further into creating a long-term concept. Includes real-world examples like the Nescafe Frape concept to bring theory to life.',
        'INTERMEDIATE',
        3.5,
        29,
        49,
        10,
        'Value Creation & Strategic Marketing'),
       ('Onboarding Fundamentals: How to Successfully Incorporate New Employees',
        'Master the essentials of onboarding to boost retention and employee satisfaction.',
        'Learn how to create a structured onboarding experience that accelerates productivity and ensures long-term success.',
        'This course dives into the core principles of effective onboarding. You’ll learn how a well-designed onboarding process can significantly improve employee retention, boost engagement, and enhance workplace satisfaction. Discover how to help new employees smoothly integrate into company culture, quickly understand their roles, and feel empowered from day one. Practical strategies, examples, and onboarding templates are included to help you implement a seamless onboarding journey.',
        'BEGINNER',
        3,
        25,
        48,
        10,
        'HR & Talent Development'),
       ('Professional Self-Assessment: Identify Barriers Holding You Back & Areas for Improvement',
        'Use self-assessment tools to unlock growth and overcome personal barriers.',
        'Gain insight into your professional strengths, weaknesses, and areas for growth using proven self-assessment techniques.',
        'This course provides practical tools and frameworks to help you evaluate your professional performance and identify what’s holding you back. You’ll explore techniques like performance and need assessments, and learn to apply the method of deduction to draw clear conclusions about your development. Emphasis is placed on the role of efficiency and practical application in everyday work. Ideal for professionals looking to grow in self-awareness, accountability, and effectiveness.',
        'BEGINNER',
        2.5,
        25,
        47,
        10,
        'Personal Growth & Career Development'),
       ('Establishing Continuous Business Excellence in Your Company',
        'Create a high-performance culture through proven excellence frameworks.',
        'Learn how to implement continuous improvement models to optimize operations, team alignment, and long-term success.',
        'This course is designed for professionals and leaders who want to embed a culture of excellence within their organization. You’ll explore powerful models such as the Effective Meetings Model, AB model, DF model, and pre/post evaluation frameworks. Learn how to map and address organizational disproportions and improve performance across all departments. By the end, you’ll be equipped with tools to drive consistency, accountability, and strategic growth across your company.',
        'ADVANCED',
        4,
        39,
        49,
        10,
        'Operational Excellence & Leadership'),
       ('High-Performing Teams and Systems: Organizational Success Through Structure',
        'Build efficient, structured teams and systems that drive sustainable organizational success.',
        'Explore how to structure your teams and systems to optimize performance, efficiency, and collaboration across your organization.',
        'This course focuses on creating high-performing teams by implementing structured systems and eliminating inefficiencies. Learn how to apply a systematic approach to team organization, overcome the pitfalls of working in silos, and increase alignment through effective meetings, communication, confrontation, and decision-making practices. Ideal for team leaders and managers seeking a structured path to operational excellence.',
        'INTERMEDIATE',
        3.5,
        32,
        48,
        10,
        'Team Management & Organizational Structure');
