package com.shifterwebapp.shifter.collection.domain.learningpath.enums;

public enum PersonalizedLearningPathType {
    SYSTEM_RECOMMENDATION,      // A recommendation generated by the system
    ADJUSTED_LEARNING_PATH      // A learning path that has been adjusted because a user already has some course from the base learning path
}
